name: Jekyll Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Show installed gems (debug)
        run: gem list

      - name: Build the Jekyll site (debug)
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: joshlarsen/jekyll4-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}


# name: Jekyll Deploy
#
# on:
#   push:
#     branches:
#       - main
#
# jobs:
#
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: GitHub Checkout
#         uses: actions/checkout@v1
#       - name: Bundler Cache
#         uses: actions/cache@v4
#         with:
#           path: vendor/bundle
#           key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-gems-
#       - name: validate-bio-json-file
#         uses: limitusus/json-syntax-check@v1
#         with:
#           pattern: "\\bio.json$"
#       - name: Build & Deploy to GitHub Pages
#         uses: joshlarsen/jekyll4-deploy-gh-pages@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
#           GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
